//! Confirmation and Mutation Audit pipeline integration tests (FR-017, FR-033, Q6, Q7, Q8).

mod common;

use axum::response::IntoResponse;
use common::idp::{AudienceResponse, MockIdp};
use common::{ElicitationResponse, McpProcess, SENTINEL_APP_TOKEN, ScratchDir, spawn_mock};
use microsoft_defender_mcp_server::auth::Audience;
use serde_json::{Value, json};
use std::sync::Arc;
const MACHINE: &str = "1e5bc9d7e413ddd7902c2932e418702b84d0cc07";
const ACTION_ID: &str = "7327b54fd718525cbca07dacde913b5ac3c85673";
const COMMENT: &str = "Incident 4124 triage collection";
const SHA1: &str = "87662bc3d60e4200ceaf7aae249d1c343f4b83c9";

fn collect_args() -> Value {
    json!({
        "action": "collect_investigation_package",
        "machine_id": MACHINE,
        "comment": COMMENT,
    })
}

fn create_upstream_app() -> axum::Router {
    axum::Router::new().fallback(|req: axum::extract::Request| async move {
        let method = req.method().to_string();
        let path = req.uri().path().to_string();

        if method == "POST" && path.ends_with("/oauth2/v2.0/token") {
            axum::Json(json!({
                "token_type": "Bearer",
                "access_token": SENTINEL_APP_TOKEN,
                "expires_in": 3600
            }))
            .into_response()
        } else if method == "DELETE" || (method == "POST" && path == "/api/indicators/BatchDelete")
        {
            axum::http::StatusCode::NO_CONTENT.into_response()
        } else {
            axum::Json(json!({
                "id": ACTION_ID,
                "status": "Pending",
                "type": "CollectInvestigationPackage",
                "value": []
            }))
            .into_response()
        }
    })
}

// =========================================================================
// Group 1: confirm_ (Q6)
// =========================================================================

#[tokio::test]
async fn test_confirm_accepted_runs_upstream_and_records_elicitations() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("confirm-accept");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::initialize_with_elicitation(
        &[
            "--enable-live-response",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
        ElicitationResponse::AcceptConfirm,
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_ne!(res["result"]["isError"], json!(true), "{res:?}");
    assert_eq!(res["result"]["structuredContent"]["id"], ACTION_ID);

    // 1 upstream hit to the collection endpoint
    mock.assert_hits(
        &format!("/api/machines/{MACHINE}/collectInvestigationPackage"),
        1,
    );

    // Elicitation message asserts prompt text per template
    let messages = proc.recorded_elicitations();
    assert_eq!(messages.len(), 1, "expected 1 elicitation message");
    let msg = &messages[0];
    assert!(msg.contains("Confirm destructive Microsoft Defender action"));
    assert!(msg.contains("Tool:    defender_response"));
    assert!(msg.contains("Action:  collect_investigation_package"));
    assert!(msg.contains(MACHINE));
    assert!(msg.contains(COMMENT));
    assert!(msg.contains("Acting as:"));
    assert!(
        msg.contains("This request was generated by an AI agent. Approve only if you intended it.")
    );

    assert!(proc.shutdown().success());
}

#[tokio::test]
async fn test_confirm_declined_via_false_returns_not_confirmed_and_zero_hits() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("confirm-false");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::initialize_with_elicitation(
        &[
            "--enable-live-response",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
        ElicitationResponse::AcceptReject,
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_eq!(res["result"]["isError"], json!(true));
    assert_eq!(
        res["result"]["structuredContent"]["code"],
        json!("not_confirmed")
    );

    mock.assert_hits(
        &format!("/api/machines/{MACHINE}/collectInvestigationPackage"),
        0,
    );
    assert!(proc.shutdown().success());
}

#[tokio::test]
async fn test_confirm_declined_returns_not_confirmed_and_zero_hits() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("confirm-decline");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::initialize_with_elicitation(
        &[
            "--enable-live-response",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
        ElicitationResponse::Decline,
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_eq!(res["result"]["isError"], json!(true));
    assert_eq!(
        res["result"]["structuredContent"]["code"],
        json!("not_confirmed")
    );

    mock.assert_hits(
        &format!("/api/machines/{MACHINE}/collectInvestigationPackage"),
        0,
    );
    assert!(proc.shutdown().success());
}

#[tokio::test]
async fn test_confirm_cancelled_returns_not_confirmed_and_zero_hits() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("confirm-cancel");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::initialize_with_elicitation(
        &[
            "--enable-live-response",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
        ElicitationResponse::Cancel,
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_eq!(res["result"]["isError"], json!(true));
    assert_eq!(
        res["result"]["structuredContent"]["code"],
        json!("not_confirmed")
    );

    mock.assert_hits(
        &format!("/api/machines/{MACHINE}/collectInvestigationPackage"),
        0,
    );
    assert!(proc.shutdown().success());
}

#[tokio::test]
async fn test_confirm_timeout_returns_not_confirmed_and_zero_hits() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("confirm-timeout");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::initialize_with_elicitation(
        &[
            "--enable-live-response",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
            ("DEFENDER_TEST_ELICITATION_TIMEOUT_MS", "200"),
        ],
        ElicitationResponse::NoAnswer,
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_eq!(res["result"]["isError"], json!(true));
    assert_eq!(
        res["result"]["structuredContent"]["code"],
        json!("not_confirmed")
    );

    mock.assert_hits(
        &format!("/api/machines/{MACHINE}/collectInvestigationPackage"),
        0,
    );
    assert!(proc.shutdown().success());
}

#[tokio::test]
async fn test_confirm_unavailable_without_client_elicitation() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("confirm-unavail");
    let audit_file = scratch.0.join("audit.jsonl");

    // Client without elicitation capability
    let mut proc = McpProcess::start(
        &[
            "--enable-live-response",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_eq!(res["result"]["isError"], json!(true));
    let content = &res["result"]["structuredContent"];
    assert_eq!(content["code"], json!("confirmation_unavailable"));
    assert!(
        content["error"]
            .as_str()
            .unwrap()
            .contains("--disable-human-confirmation")
    );

    mock.assert_hits(
        &format!("/api/machines/{MACHINE}/collectInvestigationPackage"),
        0,
    );
    assert!(proc.shutdown().success());
}

#[tokio::test]
async fn test_confirm_disabled_runs_action_prints_warning_and_records_turned_off() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("confirm-off");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::start(
        &[
            "--enable-live-response",
            "--disable-human-confirmation",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_ne!(res["result"]["isError"], json!(true), "{res:?}");
    assert_eq!(res["result"]["structuredContent"]["id"], ACTION_ID);

    mock.assert_hits(
        &format!("/api/machines/{MACHINE}/collectInvestigationPackage"),
        1,
    );

    let stderr = proc.captured_stderr();
    assert!(
        stderr.contains("WARNING: human confirmation for destructive actions is turned OFF"),
        "expected startup WARNING on stderr: {stderr}"
    );

    assert!(proc.shutdown().success());

    // Check audit record carries confirmation: "turned_off"
    let records = read_audit_records(&audit_file);
    assert!(!records.is_empty());
    for rec in &records {
        assert_eq!(rec["confirmation"], "turned_off");
    }
}

// =========================================================================
// Group 2: gate_ (Q7)
// =========================================================================

#[tokio::test]
async fn test_gate_read_only_returns_read_only_violation_and_zero_hits() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("gate-ro");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::start(
        &[
            "--read-only",
            "--enable-live-response",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_eq!(res["result"]["isError"], json!(true));
    assert_eq!(
        res["result"]["structuredContent"]["code"],
        json!("read_only_violation")
    );

    mock.assert_hits(
        &format!("/api/machines/{MACHINE}/collectInvestigationPackage"),
        0,
    );
    assert!(proc.shutdown().success());
}

#[tokio::test]
async fn test_gate_category_disabled_returns_category_disabled_and_zero_hits() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("gate-cat-off");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::start(
        &["--audit-log", audit_file.to_str().unwrap()],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_eq!(res["result"]["isError"], json!(true));
    assert_eq!(
        res["result"]["structuredContent"]["code"],
        json!("category_disabled")
    );

    mock.assert_hits(
        &format!("/api/machines/{MACHINE}/collectInvestigationPackage"),
        0,
    );
    assert!(proc.shutdown().success());
}

fn device_response_actions_list() -> Vec<(&'static str, Value)> {
    vec![
        (
            "isolate",
            json!({ "action": "isolate", "machine_id": MACHINE, "comment": COMMENT }),
        ),
        (
            "unisolate",
            json!({ "action": "unisolate", "machine_id": MACHINE, "comment": COMMENT }),
        ),
        (
            "restrict_app_execution",
            json!({ "action": "restrict_app_execution", "machine_id": MACHINE, "comment": COMMENT }),
        ),
        (
            "unrestrict_app_execution",
            json!({ "action": "unrestrict_app_execution", "machine_id": MACHINE, "comment": COMMENT }),
        ),
        (
            "run_av_scan",
            json!({ "action": "run_av_scan", "machine_id": MACHINE, "scan_type": "Quick", "comment": COMMENT }),
        ),
        (
            "cancel_machine_action",
            json!({ "action": "cancel_machine_action", "action_id": ACTION_ID, "comment": COMMENT }),
        ),
        (
            "start_investigation",
            json!({ "action": "start_investigation", "machine_id": MACHINE, "comment": COMMENT }),
        ),
        (
            "tag_add",
            json!({ "action": "tag_add", "machine_id": MACHINE, "tag": "test-tag", "comment": COMMENT }),
        ),
        (
            "tag_remove",
            json!({ "action": "tag_remove", "machine_id": MACHINE, "tag": "test-tag", "comment": COMMENT }),
        ),
        (
            "set_device_value",
            json!({ "action": "set_device_value", "machine_id": MACHINE, "device_value": "High", "comment": COMMENT }),
        ),
        (
            "offboard",
            json!({ "action": "offboard", "machine_id": MACHINE, "comment": COMMENT }),
        ),
    ]
}

fn indicators_actions_list() -> Vec<(&'static str, Value)> {
    vec![
        (
            "submit",
            json!({
                "action": "submit",
                "indicator_value": "192.0.2.1",
                "indicator_type": "IpAddress",
                "indicator_action": "Audit",
                "title": "Suspicious IP",
                "description": "Suspicious IP indicator",
                "comment": COMMENT,
            }),
        ),
        (
            "delete",
            json!({
                "action": "delete",
                "indicator_id": "ind-12345",
                "comment": COMMENT,
            }),
        ),
        (
            "batch_delete",
            json!({
                "action": "batch_delete",
                "indicator_ids": ["ind-1", "ind-2"],
                "comment": COMMENT,
            }),
        ),
    ]
}

fn triage_actions_list() -> Vec<(&'static str, Value)> {
    vec![
        (
            "endpoint_alert_update",
            json!({ "action": "endpoint_alert_update", "id": "alert-1", "status": "inProgress", "justification": COMMENT }),
        ),
        (
            "endpoint_alert_batch_update",
            json!({ "action": "endpoint_alert_batch_update", "ids": ["alert-1", "alert-2"], "status": "inProgress", "justification": COMMENT }),
        ),
        (
            "endpoint_alert_comment",
            json!({ "action": "endpoint_alert_comment", "id": "alert-1", "comment": "Comment on alert", "justification": COMMENT }),
        ),
        (
            "xdr_alert_update",
            json!({ "action": "xdr_alert_update", "id": "alert-xdr-1", "status": "inProgress", "justification": COMMENT }),
        ),
        (
            "xdr_alert_comment",
            json!({ "action": "xdr_alert_comment", "id": "alert-xdr-1", "comment": "Comment on xdr alert", "justification": COMMENT }),
        ),
        (
            "xdr_incident_update",
            json!({ "action": "xdr_incident_update", "id": "inc-1", "status": "inProgress", "justification": COMMENT }),
        ),
        (
            "xdr_incident_comment",
            json!({ "action": "xdr_incident_comment", "id": "inc-1", "comment": "Comment on incident", "justification": COMMENT }),
        ),
    ]
}

#[tokio::test]
async fn test_gate_device_response_read_only_and_category_disabled() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("gate-device");
    let audit_file_ro = scratch.0.join("audit-ro.jsonl");
    let audit_file_cat = scratch.0.join("audit-cat.jsonl");

    let actions = device_response_actions_list();

    // 1. read_only_violation under --read-only
    {
        let mut proc = McpProcess::start(
            &[
                "--read-only",
                "--enable-device-response",
                "--enable-offboarding",
                "--audit-log",
                audit_file_ro.to_str().unwrap(),
            ],
            &[
                ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
                ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
            ],
        );

        for (action, args) in &actions {
            let res = proc.call_tool("defender_device_response", args.clone());
            assert_eq!(
                res["result"]["isError"],
                json!(true),
                "action {action} must fail under read_only"
            );
            assert_eq!(
                res["result"]["structuredContent"]["code"],
                json!("read_only_violation"),
                "action {action} must return read_only_violation"
            );
        }

        assert_eq!(mock.total_hits(), 0, "read_only calls make 0 hits");
        assert!(proc.shutdown().success());

        let records = read_audit_records(&audit_file_ro);
        assert_eq!(
            records.len(),
            actions.len(),
            "each call must write 1 audit record"
        );
        for rec in &records {
            assert_eq!(rec["phase"], "final");
            assert_eq!(rec["result"]["kind"], "rejected");
            assert_eq!(rec["result"]["reason"], "read_only");
        }
    }

    // 2. category_disabled without --enable-device-response
    {
        let mut proc = McpProcess::start(
            &["--audit-log", audit_file_cat.to_str().unwrap()],
            &[
                ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
                ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
            ],
        );

        for (action, args) in &actions {
            let res = proc.call_tool("defender_device_response", args.clone());
            assert_eq!(
                res["result"]["isError"],
                json!(true),
                "action {action} must fail without category flag"
            );
            assert_eq!(
                res["result"]["structuredContent"]["code"],
                json!("category_disabled"),
                "action {action} must return category_disabled"
            );
        }

        assert_eq!(mock.total_hits(), 0, "category_disabled calls make 0 hits");
        assert!(proc.shutdown().success());

        let records = read_audit_records(&audit_file_cat);
        assert_eq!(
            records.len(),
            actions.len(),
            "each call must write 1 audit record"
        );
        for rec in &records {
            assert_eq!(rec["phase"], "final");
            assert_eq!(rec["result"]["kind"], "rejected");
            assert_eq!(rec["result"]["reason"], "category_disabled");
        }
    }
}

#[tokio::test]
async fn test_gate_indicators_read_only_and_category_disabled() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("gate-ind");
    let audit_file_ro = scratch.0.join("audit-ro.jsonl");
    let audit_file_cat = scratch.0.join("audit-cat.jsonl");

    let actions = indicators_actions_list();

    // 1. read_only_violation under --read-only
    {
        let mut proc = McpProcess::start(
            &[
                "--read-only",
                "--enable-indicators",
                "--audit-log",
                audit_file_ro.to_str().unwrap(),
            ],
            &[
                ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
                ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
            ],
        );

        for (action, args) in &actions {
            let res = proc.call_tool("defender_indicators", args.clone());
            assert_eq!(res["result"]["isError"], json!(true));
            assert_eq!(
                res["result"]["structuredContent"]["code"],
                json!("read_only_violation"),
                "action {action} must return read_only_violation"
            );
        }

        assert_eq!(mock.total_hits(), 0);
        assert!(proc.shutdown().success());

        let records = read_audit_records(&audit_file_ro);
        assert_eq!(records.len(), actions.len());
        for rec in &records {
            assert_eq!(rec["phase"], "final");
            assert_eq!(rec["result"]["kind"], "rejected");
            assert_eq!(rec["result"]["reason"], "read_only");
        }
    }

    // 2. category_disabled without --enable-indicators
    {
        let mut proc = McpProcess::start(
            &["--audit-log", audit_file_cat.to_str().unwrap()],
            &[
                ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
                ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
            ],
        );

        for (action, args) in &actions {
            let res = proc.call_tool("defender_indicators", args.clone());
            assert_eq!(res["result"]["isError"], json!(true));
            assert_eq!(
                res["result"]["structuredContent"]["code"],
                json!("category_disabled"),
                "action {action} must return category_disabled"
            );
        }

        assert_eq!(mock.total_hits(), 0);
        assert!(proc.shutdown().success());

        let records = read_audit_records(&audit_file_cat);
        assert_eq!(records.len(), actions.len());
        for rec in &records {
            assert_eq!(rec["phase"], "final");
            assert_eq!(rec["result"]["kind"], "rejected");
            assert_eq!(rec["result"]["reason"], "category_disabled");
        }
    }
}

#[tokio::test]
async fn test_gate_triage_read_only_and_category_disabled() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("gate-triage");
    let audit_file_ro = scratch.0.join("audit-ro.jsonl");
    let audit_file_cat = scratch.0.join("audit-cat.jsonl");

    let actions = triage_actions_list();

    // 1. read_only_violation under --read-only
    {
        let mut proc = McpProcess::start(
            &[
                "--read-only",
                "--enable-triage",
                "--audit-log",
                audit_file_ro.to_str().unwrap(),
            ],
            &[
                ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
                ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
            ],
        );

        for (action, args) in &actions {
            let res = proc.call_tool("defender_triage", args.clone());
            assert_eq!(res["result"]["isError"], json!(true));
            assert_eq!(
                res["result"]["structuredContent"]["code"],
                json!("read_only_violation"),
                "action {action} must return read_only_violation"
            );
        }

        assert_eq!(mock.total_hits(), 0);
        assert!(proc.shutdown().success());

        let records = read_audit_records(&audit_file_ro);
        assert_eq!(records.len(), actions.len());
        for rec in &records {
            assert_eq!(rec["phase"], "final");
            assert_eq!(rec["result"]["kind"], "rejected");
            assert_eq!(rec["result"]["reason"], "read_only");
        }
    }

    // 2. category_disabled without --enable-triage
    {
        let mut proc = McpProcess::start(
            &["--audit-log", audit_file_cat.to_str().unwrap()],
            &[
                ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
                ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
            ],
        );

        for (action, args) in &actions {
            let res = proc.call_tool("defender_triage", args.clone());
            assert_eq!(res["result"]["isError"], json!(true));
            assert_eq!(
                res["result"]["structuredContent"]["code"],
                json!("category_disabled"),
                "action {action} must return category_disabled"
            );
        }

        assert_eq!(mock.total_hits(), 0);
        assert!(proc.shutdown().success());

        let records = read_audit_records(&audit_file_cat);
        assert_eq!(records.len(), actions.len());
        for rec in &records {
            assert_eq!(rec["phase"], "final");
            assert_eq!(rec["result"]["kind"], "rejected");
            assert_eq!(rec["result"]["reason"], "category_disabled");
        }
    }
}

// =========================================================================
// Group 3: audit_ (Q8)
// =========================================================================

fn read_audit_records(path: &std::path::Path) -> Vec<Value> {
    let content = std::fs::read_to_string(path).unwrap_or_default();
    content
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| serde_json::from_str(l).expect("audit record is JSON"))
        .collect()
}

#[tokio::test]
async fn test_audit_file_and_directory_permissions() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("audit-perms");
    let audit_dir = scratch.0.join("nested");
    let audit_file = audit_dir.join("audit.jsonl");

    let mut proc = McpProcess::initialize_with_elicitation(
        &[
            "--enable-live-response",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
        ElicitationResponse::AcceptConfirm,
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_ne!(res["result"]["isError"], json!(true));
    assert!(proc.shutdown().success());

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let file_meta = std::fs::metadata(&audit_file).expect("audit file metadata");
        let dir_meta = std::fs::metadata(&audit_dir).expect("audit dir metadata");
        assert_eq!(
            file_meta.permissions().mode() & 0o777,
            0o600,
            "file mode must be 0600"
        );
        assert_eq!(
            dir_meta.permissions().mode() & 0o777,
            0o700,
            "dir mode must be 0700"
        );
    }
}

#[tokio::test]
async fn test_audit_intent_then_outcome_share_attempt_id() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("audit-intent-outcome");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::initialize_with_elicitation(
        &[
            "--enable-live-response",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
        ElicitationResponse::AcceptConfirm,
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_ne!(res["result"]["isError"], json!(true));
    assert!(proc.shutdown().success());

    let records = read_audit_records(&audit_file);
    assert_eq!(
        records.len(),
        2,
        "expected intent and outcome records: {records:?}"
    );

    let intent = &records[0];
    let outcome = &records[1];

    assert_eq!(intent["phase"], "intent");
    assert_eq!(outcome["phase"], "outcome");

    assert_eq!(intent["attempt_id"], outcome["attempt_id"]);
    assert_eq!(intent["tool"], "defender_response");
    assert_eq!(intent["action"], "collect_investigation_package");
    assert_eq!(intent["confirmation"], "accepted");
    assert_eq!(intent["result"]["kind"], "pending");

    assert_eq!(outcome["result"]["kind"], "submitted");
    assert_eq!(outcome["result"]["tracking_id"], ACTION_ID);
}

#[tokio::test]
async fn test_audit_rejection_writes_one_final_record() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("audit-rejection");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::initialize_with_elicitation(
        &[
            "--enable-live-response",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
        ElicitationResponse::Decline,
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_eq!(res["result"]["isError"], json!(true));
    assert!(proc.shutdown().success());

    let records = read_audit_records(&audit_file);
    assert_eq!(
        records.len(),
        1,
        "rejection must write exactly 1 record: {records:?}"
    );

    let rec = &records[0];
    assert_eq!(rec["phase"], "final");
    assert_eq!(rec["confirmation"], "declined");
    assert_eq!(rec["result"]["kind"], "declined");
}

#[test]
fn test_audit_unwritable_path_exits_nonzero_at_startup() {
    let out = common::server_command(
        &[
            "--enable-live-response",
            "--audit-log",
            "/dev/null/impossible_dir/audit.jsonl",
        ],
        &[],
    )
    .output()
    .expect("run server with invalid audit log path");

    assert!(
        !out.status.success(),
        "server must exit non-zero on unwritable audit path"
    );
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("is not writable:"),
        "stderr must report unwritable audit log: {stderr}"
    );
}

#[cfg(unix)]
#[tokio::test]
async fn test_audit_unwritable_midrun_rejects_with_audit_unavailable_and_zero_hits() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("audit-fifo");
    let fifo_path = scratch.0.join("audit.fifo");
    let _ = std::fs::create_dir_all(&scratch.0);

    let status = std::process::Command::new("mkfifo")
        .arg(&fifo_path)
        .status()
        .expect("run mkfifo");
    assert!(status.success(), "mkfifo succeeded");

    // Background thread that holds read end during startup open and closes it before tool call
    let (tx, rx) = tokio::sync::oneshot::channel();
    let fifo_clone = fifo_path.clone();
    let reader_handle = std::thread::spawn(move || {
        let f = std::fs::File::open(&fifo_clone).expect("open fifo read");
        let _ = rx.blocking_recv();
        drop(f);
    });

    let mut proc = McpProcess::initialize_with_elicitation(
        &[
            "--enable-live-response",
            "--audit-log",
            fifo_path.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
        ElicitationResponse::AcceptConfirm,
    );

    // Close the read end so subsequent writes fail with EPIPE
    let _ = tx.send(());
    reader_handle.join().unwrap();

    let res = proc.call_tool("defender_response", collect_args());
    assert_eq!(res["result"]["isError"], json!(true));
    assert_eq!(
        res["result"]["structuredContent"]["code"],
        json!("audit_unavailable")
    );

    mock.assert_hits(
        &format!("/api/machines/{MACHINE}/collectInvestigationPackage"),
        0,
    );
    assert!(proc.shutdown().success());
}

#[tokio::test]
async fn test_audit_records_still_written_with_stderr_null() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("audit-stderr-null");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::start_with_null_stderr(
        &[
            "--enable-live-response",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
        true,
        ElicitationResponse::AcceptConfirm,
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_ne!(res["result"]["isError"], json!(true));
    assert!(proc.shutdown().success());

    let records = read_audit_records(&audit_file);
    assert_eq!(
        records.len(),
        2,
        "audit records must still be written when stderr is null"
    );
}

#[tokio::test]
async fn test_audit_no_sentinel_matches() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("audit-sentinel");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::initialize_with_elicitation(
        &[
            "--enable-live-response",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
        ElicitationResponse::AcceptConfirm,
    );

    let res = proc.call_tool("defender_response", collect_args());
    assert_ne!(res["result"]["isError"], json!(true));
    assert!(proc.shutdown().success());

    let content = std::fs::read_to_string(&audit_file).expect("read audit file");
    assert!(
        !content.contains("SENTINEL-"),
        "audit file must contain zero SENTINEL- credentials, found matches in:\n{content}"
    );
}

// =========================================================================
// T038: confirm_ and audit targets for defender_indicators (US3)
// =========================================================================

#[tokio::test]
async fn test_confirm_indicators_batch_delete_lists_all_ids_in_elicitation() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("confirm-batch-del");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::initialize_with_elicitation(
        &[
            "--enable-indicators",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
        ElicitationResponse::AcceptConfirm,
    );

    let res = proc.call_tool(
        "defender_indicators",
        json!({
            "action": "batch_delete",
            "indicator_ids": ["ind-001", "ind-002", "ind-003"],
            "comment": COMMENT,
        }),
    );
    assert_ne!(res["result"]["isError"], json!(true), "{res:?}");

    let elicitations = proc.recorded_elicitations();
    assert_eq!(
        elicitations.len(),
        1,
        "expected exactly 1 elicitation message"
    );
    let msg = &elicitations[0];
    assert!(msg.contains("defender_indicators"));
    assert!(msg.contains("batch_delete"));
    assert!(
        msg.contains("ind-001"),
        "elicitation must list ind-001: {msg}"
    );
    assert!(
        msg.contains("ind-002"),
        "elicitation must list ind-002: {msg}"
    );
    assert!(
        msg.contains("ind-003"),
        "elicitation must list ind-003: {msg}"
    );

    assert!(proc.shutdown().success());
}

#[tokio::test]
async fn test_audit_targets_for_indicators() {
    let mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("audit-targets-ind");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::initialize_with_elicitation(
        &[
            "--enable-indicators",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
        ElicitationResponse::AcceptConfirm,
    );

    // 1. submit -> indicator_value
    let res1 = proc.call_tool(
        "defender_indicators",
        json!({
            "action": "submit",
            "indicator_value": "198.51.100.1",
            "indicator_type": "IpAddress",
            "indicator_action": "Audit",
            "title": "Test IP",
            "description": "Test indicator",
            "comment": COMMENT,
        }),
    );
    assert_ne!(res1["result"]["isError"], json!(true));

    // 2. delete -> indicator_id
    let res2 = proc.call_tool(
        "defender_indicators",
        json!({
            "action": "delete",
            "indicator_id": "ind-del-42",
            "comment": COMMENT,
        }),
    );
    assert_ne!(res2["result"]["isError"], json!(true));

    assert!(proc.shutdown().success());

    let records = read_audit_records(&audit_file);
    assert_eq!(records.len(), 4, "2 calls = 4 records (intent + outcome)");

    // Submit target check
    let sub_intent = &records[0];
    let sub_targets = sub_intent["targets"].as_array().expect("targets array");
    assert_eq!(sub_targets.len(), 1);
    assert_eq!(sub_targets[0]["kind"], "indicator_value");
    assert_eq!(sub_targets[0]["value"], "198.51.100.1");

    // Delete target check
    let del_intent = &records[2];
    let del_targets = del_intent["targets"].as_array().expect("targets array");
    assert_eq!(del_targets.len(), 1);
    assert_eq!(del_targets[0]["kind"], "indicator_id");
    assert_eq!(del_targets[0]["value"], "ind-del-42");
}

// =========================================================================
// T045: triage no elicitation & upstream omits justification (US4)
// =========================================================================

#[tokio::test]
async fn test_triage_no_elicitation_audit_not_applicable_upstream_omits_justification() {
    let seen_body = Arc::new(tokio::sync::Mutex::new(None));
    let seen_body_clone = seen_body.clone();

    let app = axum::Router::new().fallback(move |req: axum::extract::Request| {
        let seen = seen_body_clone.clone();
        async move {
            let path = req.uri().path().to_string();
            if path.ends_with("/oauth2/v2.0/token") {
                return axum::Json(json!({
                    "token_type": "Bearer",
                    "access_token": SENTINEL_APP_TOKEN,
                    "expires_in": 3600
                }))
                .into_response();
            }
            let bytes = axum::body::to_bytes(req.into_body(), 1024 * 1024)
                .await
                .unwrap_or_default();
            let body: Value = serde_json::from_slice(&bytes).unwrap_or(Value::Null);
            *seen.lock().await = Some(body);
            axum::Json(json!({ "id": "alert-1", "status": "InProgress" })).into_response()
        }
    });

    let mock = spawn_mock(app).await;
    let scratch = ScratchDir::new("triage-audit-no-prompt");
    let audit_file = scratch.0.join("audit.jsonl");

    let mut proc = McpProcess::initialize_with_elicitation(
        &[
            "--enable-triage",
            "--audit-log",
            audit_file.to_str().unwrap(),
        ],
        &[
            ("DEFENDER_ENDPOINT_BASE_URL", &mock.base_url),
            ("DEFENDER_AUTHORITY_BASE_URL", &mock.base_url),
        ],
        ElicitationResponse::AcceptConfirm,
    );

    let triage_justification = "Operational justification for incident alert update";
    let res = proc.call_tool(
        "defender_triage",
        json!({
            "action": "endpoint_alert_update",
            "id": "alert-1",
            "status": "inProgress",
            "justification": triage_justification,
        }),
    );
    assert_ne!(res["result"]["isError"], json!(true), "{res:?}");

    // No elicitation prompted
    assert!(
        proc.recorded_elicitations().is_empty(),
        "defender_triage must send NO elicitation even when client declares support"
    );

    // Upstream body never contains justification
    let upstream_body = seen_body
        .lock()
        .await
        .clone()
        .expect("upstream request received");
    let upstream_str = upstream_body.to_string();
    assert!(
        !upstream_str.contains(triage_justification),
        "upstream body must never contain justification: {upstream_str}"
    );
    assert!(
        !upstream_str.contains("justification"),
        "upstream body must never contain key 'justification': {upstream_str}"
    );

    assert!(proc.shutdown().success());

    // Audit record has confirmation: "not_applicable" and justification set
    let records = read_audit_records(&audit_file);
    assert_eq!(records.len(), 2, "intent and outcome records expected");
    for rec in &records {
        assert_eq!(
            rec["confirmation"], "not_applicable",
            "confirmation must be 'not_applicable'"
        );
        assert_eq!(
            rec["justification"], triage_justification,
            "justification must be recorded in audit log"
        );
    }
}

// =========================================================================
// T062: Credential-Exclusion Sweep (SC-006, SC-011)
// =========================================================================

fn all_26_mutating_actions() -> Vec<(&'static str, &'static str, Value, Value)> {
    vec![
        // defender_response (5)
        (
            "defender_response",
            "collect_investigation_package",
            json!({ "action": "collect_investigation_package", "machine_id": MACHINE, "comment": COMMENT }),
            json!({ "action": "collect_investigation_package", "machine_id": MACHINE, "comment": "short" }),
        ),
        (
            "defender_response",
            "stop_and_quarantine_file",
            json!({ "action": "stop_and_quarantine_file", "machine_id": MACHINE, "sha1": SHA1, "comment": COMMENT }),
            json!({ "action": "stop_and_quarantine_file", "machine_id": MACHINE, "sha1": SHA1, "comment": "short" }),
        ),
        (
            "defender_response",
            "live_response_run",
            json!({ "action": "live_response_run", "machine_id": MACHINE, "commands": [{"type": "RunScript", "params": [{"key": "ScriptName", "value": "test.ps1"}]}], "comment": COMMENT }),
            json!({ "action": "live_response_run", "machine_id": MACHINE, "commands": [], "comment": "short" }),
        ),
        (
            "defender_response",
            "upload_library_file",
            json!({ "action": "upload_library_file", "file_name": "tool.ps1", "file_content": "V3JpdGUtSG9zdA==", "description": "script", "comment": COMMENT }),
            json!({ "action": "upload_library_file", "file_name": "tool.ps1", "file_content": "V3JpdGUtSG9zdA==", "description": "script", "comment": "short" }),
        ),
        (
            "defender_response",
            "library_file_delete",
            json!({ "action": "library_file_delete", "file_name": "tool.ps1", "comment": COMMENT }),
            json!({ "action": "library_file_delete", "file_name": "tool.ps1", "comment": "short" }),
        ),
        // defender_device_response (11)
        (
            "defender_device_response",
            "isolate",
            json!({ "action": "isolate", "machine_id": MACHINE, "comment": COMMENT }),
            json!({ "action": "isolate", "machine_id": MACHINE, "comment": "short" }),
        ),
        (
            "defender_device_response",
            "unisolate",
            json!({ "action": "unisolate", "machine_id": MACHINE, "comment": COMMENT }),
            json!({ "action": "unisolate", "machine_id": MACHINE, "comment": "short" }),
        ),
        (
            "defender_device_response",
            "restrict_app_execution",
            json!({ "action": "restrict_app_execution", "machine_id": MACHINE, "comment": COMMENT }),
            json!({ "action": "restrict_app_execution", "machine_id": MACHINE, "comment": "short" }),
        ),
        (
            "defender_device_response",
            "unrestrict_app_execution",
            json!({ "action": "unrestrict_app_execution", "machine_id": MACHINE, "comment": COMMENT }),
            json!({ "action": "unrestrict_app_execution", "machine_id": MACHINE, "comment": "short" }),
        ),
        (
            "defender_device_response",
            "run_av_scan",
            json!({ "action": "run_av_scan", "machine_id": MACHINE, "scan_type": "Quick", "comment": COMMENT }),
            json!({ "action": "run_av_scan", "machine_id": MACHINE, "scan_type": "Quick", "comment": "short" }),
        ),
        (
            "defender_device_response",
            "start_investigation",
            json!({ "action": "start_investigation", "machine_id": MACHINE, "comment": COMMENT }),
            json!({ "action": "start_investigation", "machine_id": MACHINE, "comment": "short" }),
        ),
        (
            "defender_device_response",
            "cancel_machine_action",
            json!({ "action": "cancel_machine_action", "action_id": ACTION_ID, "comment": COMMENT }),
            json!({ "action": "cancel_machine_action", "action_id": ACTION_ID, "comment": "short" }),
        ),
        (
            "defender_device_response",
            "tag_add",
            json!({ "action": "tag_add", "machine_id": MACHINE, "tag": "test-tag", "comment": COMMENT }),
            json!({ "action": "tag_add", "machine_id": MACHINE, "tag": "test-tag", "comment": "short" }),
        ),
        (
            "defender_device_response",
            "tag_remove",
            json!({ "action": "tag_remove", "machine_id": MACHINE, "tag": "test-tag", "comment": COMMENT }),
            json!({ "action": "tag_remove", "machine_id": MACHINE, "tag": "test-tag", "comment": "short" }),
        ),
        (
            "defender_device_response",
            "set_device_value",
            json!({ "action": "set_device_value", "machine_id": MACHINE, "device_value": "High", "comment": COMMENT }),
            json!({ "action": "set_device_value", "machine_id": MACHINE, "device_value": "High", "comment": "short" }),
        ),
        (
            "defender_device_response",
            "offboard",
            json!({ "action": "offboard", "machine_id": MACHINE, "comment": COMMENT }),
            json!({ "action": "offboard", "machine_id": MACHINE, "comment": "short" }),
        ),
        // defender_indicators (3)
        (
            "defender_indicators",
            "submit",
            json!({ "action": "submit", "indicator_value": "192.0.2.1", "indicator_type": "IpAddress", "indicator_action": "Audit", "title": "Suspicious", "description": "Suspicious IP", "comment": COMMENT }),
            json!({ "action": "submit", "indicator_value": "192.0.2.1", "indicator_type": "IpAddress", "indicator_action": "Audit", "title": "Suspicious", "description": "Suspicious IP", "comment": "short" }),
        ),
        (
            "defender_indicators",
            "delete",
            json!({ "action": "delete", "indicator_id": "ind-12345", "comment": COMMENT }),
            json!({ "action": "delete", "indicator_id": "ind-12345", "comment": "short" }),
        ),
        (
            "defender_indicators",
            "batch_delete",
            json!({ "action": "batch_delete", "indicator_ids": ["ind-1", "ind-2"], "comment": COMMENT }),
            json!({ "action": "batch_delete", "indicator_ids": ["ind-1", "ind-2"], "comment": "short" }),
        ),
        // defender_triage (7)
        (
            "defender_triage",
            "endpoint_alert_update",
            json!({ "action": "endpoint_alert_update", "id": "alert-1", "status": "inProgress", "justification": COMMENT }),
            json!({ "action": "endpoint_alert_update", "id": "alert-1", "status": "inProgress", "justification": "short" }),
        ),
        (
            "defender_triage",
            "endpoint_alert_batch_update",
            json!({ "action": "endpoint_alert_batch_update", "ids": ["alert-1", "alert-2"], "status": "inProgress", "justification": COMMENT }),
            json!({ "action": "endpoint_alert_batch_update", "ids": ["alert-1", "alert-2"], "status": "inProgress", "justification": "short" }),
        ),
        (
            "defender_triage",
            "endpoint_alert_comment",
            json!({ "action": "endpoint_alert_comment", "id": "alert-1", "comment": "Comment on alert", "justification": COMMENT }),
            json!({ "action": "endpoint_alert_comment", "id": "alert-1", "comment": "Comment on alert", "justification": "short" }),
        ),
        (
            "defender_triage",
            "xdr_alert_update",
            json!({ "action": "xdr_alert_update", "id": "alert-xdr-1", "status": "inProgress", "justification": COMMENT }),
            json!({ "action": "xdr_alert_update", "id": "alert-xdr-1", "status": "inProgress", "justification": "short" }),
        ),
        (
            "defender_triage",
            "xdr_alert_comment",
            json!({ "action": "xdr_alert_comment", "id": "alert-xdr-1", "comment": "Comment on xdr alert", "justification": COMMENT }),
            json!({ "action": "xdr_alert_comment", "id": "alert-xdr-1", "comment": "Comment on xdr alert", "justification": "short" }),
        ),
        (
            "defender_triage",
            "xdr_incident_update",
            json!({ "action": "xdr_incident_update", "id": "inc-1", "status": "inProgress", "justification": COMMENT }),
            json!({ "action": "xdr_incident_update", "id": "inc-1", "status": "inProgress", "justification": "short" }),
        ),
        (
            "defender_triage",
            "xdr_incident_comment",
            json!({ "action": "xdr_incident_comment", "id": "inc-1", "comment": "Comment on incident", "justification": COMMENT }),
            json!({ "action": "xdr_incident_comment", "id": "inc-1", "comment": "Comment on incident", "justification": "short" }),
        ),
    ]
}

#[tokio::test]
async fn test_credential_exclusion_sweep() {
    let upstream_mock = spawn_mock(create_upstream_app()).await;
    let scratch = ScratchDir::new("cred-exclusion-sweep");
    let audit_file = scratch.0.join("audit.jsonl");

    let all_flags = &[
        "--enable-live-response",
        "--enable-device-response",
        "--enable-offboarding",
        "--enable-indicators",
        "--enable-triage",
        "--audit-log",
        audit_file.to_str().unwrap(),
    ];
    let envs = &[
        (
            "DEFENDER_ENDPOINT_BASE_URL",
            upstream_mock.base_url.as_str(),
        ),
        (
            "DEFENDER_AUTHORITY_BASE_URL",
            upstream_mock.base_url.as_str(),
        ),
        ("GRAPH_BASE_URL", upstream_mock.base_url.as_str()),
    ];

    let actions = all_26_mutating_actions();
    let mut combined_stderr = String::new();

    // 1. Mode: accepted (all 26 succeed)
    {
        let mut proc = McpProcess::initialize_with_elicitation(
            all_flags,
            envs,
            ElicitationResponse::AcceptConfirm,
        );
        for (tool, action, valid_args, _) in &actions {
            let res = proc.call_tool(tool, valid_args.clone());
            assert_ne!(
                res["result"]["isError"],
                json!(true),
                "accepted failed for {tool}.{action}: {res}"
            );
        }
        combined_stderr.push_str(&proc.captured_stderr());
        assert!(proc.shutdown().success());
    }

    // 2. Mode: declined (19 destructive fail with not_confirmed, 7 triage proceed)
    {
        let mut proc =
            McpProcess::initialize_with_elicitation(all_flags, envs, ElicitationResponse::Decline);
        for (tool, action, valid_args, _) in &actions {
            let res = proc.call_tool(tool, valid_args.clone());
            if *tool != "defender_triage" {
                assert_eq!(
                    res["result"]["isError"],
                    json!(true),
                    "destructive {tool}.{action} must be declined"
                );
                assert_eq!(
                    res["result"]["structuredContent"]["code"],
                    json!("not_confirmed")
                );
            } else {
                assert_ne!(
                    res["result"]["isError"],
                    json!(true),
                    "triage {action} does not prompt"
                );
            }
        }
        combined_stderr.push_str(&proc.captured_stderr());
        assert!(proc.shutdown().success());
    }

    // 3. Mode: rejected (all 26 fail locally due to validation error before network)
    {
        let mut proc = McpProcess::initialize_with_elicitation(
            all_flags,
            envs,
            ElicitationResponse::AcceptConfirm,
        );
        for (tool, action, _, invalid_args) in &actions {
            let res = proc.call_tool(tool, invalid_args.clone());
            assert_eq!(
                res["result"]["isError"],
                json!(true),
                "invalid input for {tool}.{action} must fail: {res}"
            );
        }
        combined_stderr.push_str(&proc.captured_stderr());
        assert!(proc.shutdown().success());
    }

    // 4. Mode: confirmation unavailable (19 destructive fail with confirmation_unavailable, 7 triage proceed)
    {
        let mut proc = McpProcess::start(all_flags, envs);
        for (tool, action, valid_args, _) in &actions {
            let res = proc.call_tool(tool, valid_args.clone());
            if *tool != "defender_triage" {
                assert_eq!(
                    res["result"]["isError"],
                    json!(true),
                    "destructive {tool}.{action} must fail when unavailable"
                );
                assert_eq!(
                    res["result"]["structuredContent"]["code"],
                    json!("confirmation_unavailable")
                );
            } else {
                assert_ne!(
                    res["result"]["isError"],
                    json!(true),
                    "triage {action} proceeds without elicitation"
                );
            }
        }
        combined_stderr.push_str(&proc.captured_stderr());
        assert!(proc.shutdown().success());
    }

    // 5. User-mode: sign-in, renewal, renewal failure through MockIdp
    let idp = MockIdp::start().await;
    // Initial token grants for startup
    idp.queue_audience_response(
        Audience::Endpoint,
        AudienceResponse::Success {
            scopes: vec!["Machine.ReadWrite".into()],
            expires_in: 0, // Immediately expired so next call triggers renewal
        },
    );
    idp.set_audience_response(
        Audience::Graph,
        AudienceResponse::Success {
            scopes: vec!["SecurityAlert.ReadWrite.All".into()],
            expires_in: 3600,
        },
    );
    // Renewal 1: succeeds (returns new tokens)
    idp.queue_audience_response(
        Audience::Endpoint,
        AudienceResponse::Success {
            scopes: vec!["Machine.ReadWrite".into()],
            expires_in: 0,
        },
    );
    // Renewal 2: fails with AADSTS700082
    idp.queue_audience_response(Audience::Endpoint, AudienceResponse::Aadsts(700082));

    let user_flags = &[
        "--auth-mode",
        "user",
        "--sign-in-flow",
        "browser",
        "--enable-live-response",
        "--audit-log",
        audit_file.to_str().unwrap(),
    ];
    let user_envs = &[
        ("DEFENDER_AUTHORITY_BASE_URL", idp.base_url.as_str()),
        ("DEFENDER_TEST_BROWSER_CMD", MockIdp::browser_cmd()),
        (
            "DEFENDER_ENDPOINT_BASE_URL",
            upstream_mock.base_url.as_str(),
        ),
        ("GRAPH_BASE_URL", upstream_mock.base_url.as_str()),
    ];

    {
        let mut proc_user = McpProcess::initialize_with_elicitation(
            user_flags,
            user_envs,
            ElicitationResponse::AcceptConfirm,
        );

        // Call 1: triggers renewal, renewal succeeds
        let res1 = proc_user.call_tool("defender_response", collect_args());
        assert_ne!(
            res1["result"]["isError"],
            json!(true),
            "user mode call with renewal must succeed: {res1}"
        );

        // Call 2: triggers renewal, renewal fails with session expired
        let res2 = proc_user.call_tool("defender_response", collect_args());
        assert_eq!(
            res2["result"]["isError"],
            json!(true),
            "renewal failure must return error"
        );
        assert_eq!(
            res2["result"]["structuredContent"]["code"],
            json!("reauthentication_required")
        );

        combined_stderr.push_str(&proc_user.captured_stderr());
        assert!(proc_user.shutdown().success());
    }

    // Extract PKCE verifier recorded by MockIdp
    let verifiers: Vec<String> = idp
        .recorded_tokens()
        .iter()
        .filter_map(|t| t.code_verifier.clone())
        .collect();
    assert!(
        !verifiers.is_empty(),
        "IdP must have recorded PKCE code verifier"
    );

    // 6. Assertions on Audit Log & captured stderr
    let records = read_audit_records(&audit_file);
    assert!(
        records.len() >= 140,
        "every mutating attempt must produce audit records, got {}",
        records.len()
    );

    let audit_content = std::fs::read_to_string(&audit_file).expect("read audit file");

    let sentinels = [
        "SENTINEL-CS-",
        "SENTINEL-AT-",
        "SENTINEL-RT-",
        "SENTINEL-CODE-",
        "SENTINEL-DC-",
    ];

    for sentinel in sentinels {
        assert!(
            !audit_content.contains(sentinel),
            "audit log must not contain sentinel {sentinel}"
        );
        assert!(
            !combined_stderr.contains(sentinel),
            "stderr must not contain sentinel {sentinel}"
        );
    }

    for verifier in &verifiers {
        assert!(
            !audit_content.contains(verifier),
            "audit log must not contain PKCE code verifier {verifier}"
        );
        assert!(
            !combined_stderr.contains(verifier),
            "stderr must not contain PKCE code verifier {verifier}"
        );
    }
}
