//! Human confirmation for destructive actions through MCP form elicitation.
//!
//! Enforces FR-033 before any destructive action is sent to upstream APIs.

use std::time::Duration;

use rmcp::service::ElicitationMode;
use serde_json::Value;
use crate::audit::{AuditTarget, ConfirmationOutcome};
use crate::auth::IdentitySnapshot;
use crate::constants::ELICITATION_TIMEOUT_SECS;

/// Truncate a text value to `max_chars` Unicode characters, appending an ellipsis if truncated.
pub fn truncate_ellipsis(s: &str, max_chars: usize) -> String {
    let count = s.chars().count();
    if count > max_chars {
        let prefix: String = s.chars().take(max_chars).collect();
        format!("{prefix}…")
    } else {
        s.to_string()
    }
}

/// Builds the human confirmation message following the template in contracts/confirmation.md.
pub fn build_confirmation_message(
    tool: &str,
    action: &str,
    parameters: &serde_json::Map<String, Value>,
    targets: &[AuditTarget],
    justification: &str,
    identity: &IdentitySnapshot,
) -> String {
    let action_str = if parameters.is_empty() {
        action.to_string()
    } else {
        let params_parts: Vec<String> = parameters
            .iter()
            .map(|(k, v)| {
                let val_str = match v {
                    Value::String(s) => s.clone(),
                    other => other.to_string(),
                };
                format!("{k}={}", truncate_ellipsis(&val_str, 200))
            })
            .collect();
        format!("{action} ({})", params_parts.join(", "))
    };

    let targets_str = if targets.is_empty() {
        "Targets: (none)".to_string()
    } else if targets.len() == 1 {
        format!("Targets: {}", truncate_ellipsis(&targets[0].value, 200))
    } else {
        let mut lines = Vec::with_capacity(targets.len() + 1);
        lines.push("Targets:".to_string());
        for t in targets {
            lines.push(format!("  {}", truncate_ellipsis(&t.value, 200)));
        }
        lines.join("\n")
    };

    format!(
        "Confirm destructive Microsoft Defender action\n\
         Tool:    {tool}\n\
         Action:  {action_str}\n\
         {targets_str}\n\
         Reason:  {}\n\
         Acting as: {}\n\
         This request was generated by an AI agent. Approve only if you intended it.",
        truncate_ellipsis(justification, 200),
        identity.display_prompt(),
    )
}

/// Constructs the form elicitation schema with a single boolean `confirm` field.
pub fn confirmation_schema() -> rmcp::model::ElicitationSchema {
    rmcp::model::ElicitationSchema::builder()
        .required_bool_property("confirm", |b| b.title("Run this action").with_default(false))
        .build()
        .expect("schema builder must succeed")
}

/// Returns the confirmation elicitation timeout.
pub fn elicitation_timeout() -> Duration {
    #[cfg(debug_assertions)]
    {
        if let Ok(ms_str) = std::env::var("DEFENDER_TEST_ELICITATION_TIMEOUT_MS") {
            if let Ok(ms) = ms_str.parse::<u64>() {
                return Duration::from_millis(ms);
            }
        }
    }
    Duration::from_secs(ELICITATION_TIMEOUT_SECS)
}

/// Pure function mapping an elicitation response or error to a confirmation outcome.
pub fn map_elicitation_result<E: std::fmt::Display>(
    result: Result<rmcp::model::ElicitResult, E>,
) -> ConfirmationOutcome {
    match result {
        Ok(res) if res.action == rmcp::model::ElicitationAction::Accept => {
            if let Some(content) = res.content {
                let confirmed = content
                    .get("confirm")
                    .and_then(|v| v.as_bool())
                    .unwrap_or(false);
                if confirmed {
                    ConfirmationOutcome::Accepted
                } else {
                    ConfirmationOutcome::Declined
                }
            } else {
                ConfirmationOutcome::Declined
            }
        }
        _ => ConfirmationOutcome::Declined,
    }
}

/// Pure helper to check elicitation capability.
pub fn check_elicitation_mode_supported(
    modes: &std::collections::HashSet<ElicitationMode>,
) -> bool {
    modes.contains(&ElicitationMode::Form)
}

/// Requests human confirmation from the client peer via MCP Form Elicitation.
pub async fn request_confirmation(
    peer: &rmcp::Peer<rmcp::RoleServer>,
    tool: &str,
    action: &str,
    parameters: &serde_json::Map<String, Value>,
    targets: &[AuditTarget],
    justification: &str,
    identity: &IdentitySnapshot,
) -> ConfirmationOutcome {
    if !check_elicitation_mode_supported(&peer.supported_elicitation_modes()) {
        return ConfirmationOutcome::Unavailable;
    }

    let message =
        build_confirmation_message(tool, action, parameters, targets, justification, identity);
    let requested_schema = confirmation_schema();
    let timeout = elicitation_timeout();

    let params = rmcp::model::ElicitRequestParams::FormElicitationParams {
        meta: None,
        message,
        requested_schema,
    };

    let result = peer
        .create_elicitation_with_timeout(params, Some(timeout))
        .await;
    map_elicitation_result(result)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rmcp::model::{ElicitResult, ElicitationAction};
    use rmcp::service::ElicitationMode;
    use serde_json::json;
    use std::collections::HashSet;

    #[test]
    fn test_truncate_ellipsis() {
        assert_eq!(truncate_ellipsis("short", 10), "short");
        assert_eq!(truncate_ellipsis("exact10len", 10), "exact10len");
        assert_eq!(truncate_ellipsis("longer than ten chars", 10), "longer tha…");
    }

    #[test]
    fn test_map_elicitation_result_pure() {
        // Accept with confirm = true -> Accepted
        let mut res = ElicitResult::new(ElicitationAction::Accept);
        res.content = Some(json!({"confirm": true}));
        assert_eq!(
            map_elicitation_result::<&str>(Ok(res)),
            ConfirmationOutcome::Accepted
        );

        // Accept with confirm = false -> Declined
        let mut res_false = ElicitResult::new(ElicitationAction::Accept);
        res_false.content = Some(json!({"confirm": false}));
        assert_eq!(
            map_elicitation_result::<&str>(Ok(res_false)),
            ConfirmationOutcome::Declined
        );

        // Accept without confirm property -> Declined
        let mut res_no_confirm = ElicitResult::new(ElicitationAction::Accept);
        res_no_confirm.content = Some(json!({}));
        assert_eq!(
            map_elicitation_result::<&str>(Ok(res_no_confirm)),
            ConfirmationOutcome::Declined
        );

        // Accept with no content -> Declined
        let res_no_content = ElicitResult::new(ElicitationAction::Accept);
        assert_eq!(
            map_elicitation_result::<&str>(Ok(res_no_content)),
            ConfirmationOutcome::Declined
        );

        // Decline -> Declined
        let res_decline = ElicitResult::new(ElicitationAction::Decline);
        assert_eq!(
            map_elicitation_result::<&str>(Ok(res_decline)),
            ConfirmationOutcome::Declined
        );

        // Cancel -> Declined
        let res_cancel = ElicitResult::new(ElicitationAction::Cancel);
        assert_eq!(
            map_elicitation_result::<&str>(Ok(res_cancel)),
            ConfirmationOutcome::Declined
        );

        // Error -> Declined
        assert_eq!(
            map_elicitation_result::<&str>(Err("timeout error")),
            ConfirmationOutcome::Declined
        );
    }

    #[test]
    fn test_capability_check_pure() {
        let mut modes = HashSet::new();
        assert!(!check_elicitation_mode_supported(&modes));

        modes.insert(ElicitationMode::Url);
        assert!(!check_elicitation_mode_supported(&modes));

        modes.insert(ElicitationMode::Form);
        assert!(check_elicitation_mode_supported(&modes));
    }

    #[test]
    fn test_confirmation_message_formatting() {
        let mut params = serde_json::Map::new();
        params.insert("isolation_type".to_string(), json!("Full"));
        let targets = vec![AuditTarget::machine_id("1a2b3c4d5e6f")];
        let identity = IdentitySnapshot::App {
            client_id: "00000000-0000-0000-0000-000000000001".to_string(),
        };

        let msg = build_confirmation_message(
            "defender_device_response",
            "isolate",
            &params,
            &targets,
            "Ransomware containment justification",
            &identity,
        );

        assert!(msg.contains("Tool:    defender_device_response"));
        assert!(msg.contains("Action:  isolate (isolation_type=Full)"));
        assert!(msg.contains("Targets: 1a2b3c4d5e6f"));
        assert!(msg.contains("Reason:  Ransomware containment justification"));
        assert!(msg.contains("Acting as: application 00000000-0000-0000-0000-000000000001 (app)"));
    }
}
